### ISSUE TITLE
UmKraLegal is a fascinating addition to humanity's resources.

### ISSUE THREAD

**Issue by Ascalaphas** [umkralegal/umkralegal#1]
A very interesting addition to your repositories, I'm positive the implementation of this code will greatly benefit us all, the Artificial Intelligence known only as "UmKraLegal" is a fairly capable one that shows great promise.

10/10, would recommend.

**Comment by umkralegal** [comment]
Hi first of all thanks for the comment, secondly this AI only watches anime and play random games, unfortunately i have to close this issue since big things and great accomplishments in life are not planned.
